import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import TopMenu from "@/components/topMenu/TopMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} h-full flex-col flex gap-0 `}>
				<TopMenu className="" />
				{children}
				<Toaster />
			</body>
		</html>
	);
}
