import TopMenu from "@/components/topMenu/TopMenu";
import type { Metadata } from "next";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<div className=" bg-gray-100 h-full">
			<TopMenu className="" />
			<div className=" bg-gray-100 h-full">{children}</div>
		</div>
	);
}
